global:
  scrape_interval: 10s
  evaluation_interval: 10s
storage:
  tsdb:
    out_of_order_time_window: 48h
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: memory-allocer
    static_configs:
      - targets:
          - memory-allocer:8080